name: Publish Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      GIT_AUTHOR_NAME: ${{ secrets.BOT_GITHUB_NAME }}
      GIT_AUTHOR_EMAIL: ${{ secrets.BOT_GITHUB_EMAIL }}
      GIT_COMMITTER_NAME: ${{ secrets.BOT_GITHUB_NAME }}
      GIT_COMMITTER_EMAIL: ${{ secrets.BOT_GITHUB_EMAIL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Configure git
        run: git config user.name "$GIT_COMMITTER_NAME" && git config user.email "$GIT_COMMITTER_EMAIL"
      - name: Build
        run: npm run build
      - name: Publish NPM Package
        run: npm run release
